### ISSUE TITLE
Installing kickstart through ui causes error

### ISSUE THREAD

**Issue by HnLn** [cultuurnet/culturefeed-kickstart#1]
When you install kickstart through the UI, it ends with an error.

This is because of https://github.com/cultuurnet/culturefeed/blob/master/culturefeed_search/lib/Drupal/Import/CultureFeedDomainImport.php#L92

A drush command is issued in the domain import and drush is not available when installing through ui.

**Comment by svenhoutmeyers** [comment]
made a hotfix with an extra drupal_is_cli() and merged in in develop and master already, will be in next release 3.4.2 as well
